REM   Script: DIO - BOAS PRÁTICAS EM BANCOS RELACIONAIS
REM   CURSO DA DIO DE SQL SERVER: BOAS PRATICAS EM BANCOS RELACIONAIS

CREATE TABLE PRODUTOS ( 
    CODIGO              NUMBER(5)               NOT NULL, 
    DESCRICAO           VARCHAR(50)             NOT NULL, 
    DATA_VENCIMENTO     DATE, 
    EAN                 VARCHAR(15)             NOT NULL, 
    IND_INATIVO         NUMBER(2) DEFAULT 0     NOT NULL 
);

ALTER TABLE PRODUTOS
    ADD CONSTRAINT PK_PRODUTOS
        PRIMARY KEY (CODIGO)
;


CREATE INDEX IDX_PRODUTOS_EAN
            ON PRODUTOS(EAN)
;


INSERT INTO PRODUTOS VALUES (1, 'Nome do Produto', SYSDATE, '1234567890', 0);


SELECT * FROM PRODUTOS;


INSERT INTO PRODUTOS (CODIGO, DESCRICAO, EAN) VALUES (2, 'Nome Produto 2', '1234578789');


SELECT *
    FROM PRODUTOS
 WHERE CODIGO = 2
 ;


SELECT COUNT(*) AS TOTAL
    FROM PRODUTOS
;


CREATE TABLE LOJA(
    CODIGO      NUMBER(5)           NOT NULL
   ,NOME        VARCHAR(50)         NOT NULL
   ,IND_INATIVO NUMBER(2) DEFAULT 0 NOT NULL
   ,CONSTRAINT LOJA_PK PRIMARY KEY (CODIGO)
)
;


INSERT INTO LOJA(CODIGO, NOME) VALUES(1000, 'Filial Nova Iguaçu');


INSERT INTO LOJA(CODIGO, NOME) VALUES(1001, 'Filial São Paulo');


INSERT INTO LOJA(CODIGO, NOME) VALUES(1002, 'Filial Recife');


CREATE TABLE ESTOQUE(
    CODIGO_PRODUTO  NUMBER(5)               NOT NULL
   ,CODIGO_FILIAL   NUMBER(5)               NOT NULL
   ,QUANTIDADE      NUMBER(9) DEFAULT 0     NOT NULL
   ,CONSTRAINT ESTOQUE_PK PRIMARY KEY(CODIGO_PRODUTO, CODIGO_FILIAL)
);



ALTER TABLE ESTOQUE
  ADD CONSTRAINT FK_ESTOQUE_PRODUTOS
    FOREIGN KEY (CODIGO_PRODUTO)
    REFERENCES PRODUTOS(CODIGO)
;


ALTER TABLE ESTOQUE
  ADD CONSTRAINT FK_ESTOQUE_LOJA
    FOREIGN KEY (CODIGO_FILIAL)
    REFERENCES LOJA(CODIGO)
;


INSERT INTO ESTOQUE (CODIGO_PRODUTO, CODIGO_FILIAL, QUANTIDADE) VALUES(1, 1000, 1);


SELECT
    E.CODIGO_FILIAL
   ,L.NOME
   ,E.CODIGO_PRODUTO
   ,P.DESCRICAO
   ,E.QUANTIDADE
  FROM ESTOQUE E INNER JOIN LOJA L
     ON E.CODIGO_FILIAL = L.CODIGO
   INNER JOIN PRODUTOS P
     ON E.CODIGO_PRODUTO = P.CODIGO
;


